# Property 로 User 생성
#spring:
#  security:
#    user:
#      name: admin
#      password: 1234
#      roles: ADMIN

# DB 연결정보 및 JPA 설정 추가
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/techstudy
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# JPA SQL 중 "?" 에 들어간 파라미터값 로그 출력
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

