#spring:
#  security:
#    user:
#      name: admin
#      password: 1234
#      roles: ADMIN

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/techstudy
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
